config/routes.rb
ChromeDevtoolsDemo::Application.routes.draw do
  root to: 'pages#home'
  get '/khodorkovsky', to: 'pages#khodorkovsky'
  get '/ip_address', to: 'pages#ip_address'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def khodorkovsky
  end

  def ip_address
    @ip = request.remote_ip
    render json: {ip: @ip}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChromeDevtoolsDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_oligarch_pics.html.erb
<span class="image-rounded-shadow" id="khodorkovsky">
  <%= image_tag 'khodorkovsky.jpg', class: 'oligarch-image spy-on-me' %>
</span>
<span class="image-rounded-shadow" id="abramovich">
  <%= image_tag 'abramovich.jpg', class: 'oligarch-image' %>
</span>
<span class="image-rounded-shadow" id="prokhorov">
  <%= image_tag 'prokhorov.jpg', class: 'oligarch-image' %>
</span>
<span class="image-rounded-shadow" id="berezovsky">
  <%= image_tag 'berezovsky.jpg', class: 'oligarch-image' %>
</span>

app/views/pages/_putin_modal.html.erb
<!-- another hover example http://jsfiddle.net/rThnm/ -->
<!-- Modal -->
<div id="putin-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Big Brother Says...</h3>
  </div>
  <div class="modal-body">
    <p>
      I am NOT watching you IP address of 
      <span id="putin-client-ip-address"></span>
    </p>
  </div>
  <div>
    <%= image_tag 'putin.jpg', class: 'putin' %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/pages/home.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
</div>


<div class="container">

  <%= render 'oligarch_pics' %>
  <h1>Oligarchs Anonymous</h1>
  <p>Where Soviet business magnates can chill out without Putin watching</p>
  <p>
    <%= link_to 'Look Around', khodorkovsky_path, class: "btn btn-primary btn-large" %>
  </p>

  <div class="oligarch-links">
    <ul>
      <li>Big Oil</li>
      <li>Manufacturing</li>
      <li>Agriculture</li>
      <li>Military</li>
    </ul>
  </div>
</div>


<%#= render 'putin_modal' %>

app/views/pages/khodorkovsky.html.erb
<div class="container">
  <div class="span12">
    <h1>Mikhail Khodorkovsky</h1>
    <%= image_tag 'khodorkovsky-1.jpg' %>
  </div>
</div>